In [1]:
import pandas as pd
import re

In [2]:
queries = pd.read_csv('/Users/nataliiaremezova/Documents/Workspace/BHT/BI/task_1/BHT_BI_WiSe2425/Task1/Data/QueriesToYT.csv')  # Replace with your file path
content_data = pd.read_csv('/Users/nataliiaremezova/Documents/Workspace/BHT/BI/task_1/BHT_BI_WiSe2425/Task1/Data/youtube_2006_month.csv')

In [3]:
# Preprocess text - lowercasing, stripping whitespace, and removing non-alphanumeric characters
def clean_text(text):
    if isinstance(text, str):
        text = text.lower().strip()
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    else:
        text = ''
    return text

queries['QUERY'] = queries['QUERY'].apply(clean_text)
content_data['title'] = content_data['title'].apply(clean_text)
content_data['tags'] = content_data['tags'].apply(lambda x: clean_text(str(x)))

# Check for matches between queries and video titles
queries['matched_titles'] = queries['QUERY'].apply(
    lambda q: content_data[content_data['title'].str.contains(q, na=False)].shape[0]
)

# Check for matches between queries and video tags
queries['matched_tags'] = queries['QUERY'].apply(
    lambda q: content_data[content_data['tags'].str.contains(q, na=False)].shape[0]
)

# Display results
print(queries[['QUERY', 'matched_titles', 'matched_tags']].head())

                            QUERY  matched_titles  matched_tags
0                     jake peyton               0             0
1             bush drinking video               0             0
2  cant stop scratching my vagina               0             0
3                      vid idiots               0             0
4                 naruto websites               0             0

In [5]:
# Filter queries with matched titles or tags greater than 0
matches = queries[(queries['matched_titles'] > 0) | (queries['matched_tags'] > 0)]

# Remove duplicate rows based on the 'QUERY' column
matches = matches.drop_duplicates(subset='QUERY')

# Display the filtered and deduplicated results
print(matches[['QUERY', 'matched_titles', 'matched_tags']])

                        QUERY  matched_titles  matched_tags
67                freerunning               0             2
72                       culo               1             1
131              the simpsons               1             1
134             myspace movie               0             1
171        brokeback mountain               1             2
200                   beatbox               4             5
250                      pedo               1             1
265              chuck norris               0             2
269                  my space               0             1
299   transformers theme song               0             1
379            something blue               1             0
578                  vogueing               0             1
602                    pacman               0             1
657                       tit              17            22
661         we are scientists               0             3
698                     naked              14            17
729                   pokemon               0             2
730             forever young               1             1
830              michael alig               0             1
904                     utube               3            16
927                 brokeback               1             2
1127                    boobs               0             1
1151                tech deck               0             1
1196              viral video               0             1
1214                     tube               3            18
1297              who are you               1             0
1304                    booty               1             0
1337                      you             113           119
1382               ronaldinho               1             7
1462                     sexy               3            18
1497                    lezbo               1             0
1564              music video             115           205
1587                  topless               0             1
1624                     huge               0             1
1717                   naruto               0             3
1724                   vegeta               2             5
1729                  shakira               0             2
1838           sleater kinney               0             3
1857                    kimbo               0             2
1883        myspace the movie               1             1
1975                     jeep               1             1

In [11]:
matches.to_excel('../Data/matches.xlsx')

In [6]:
# Filter queries with matched titles or tags greater than 0
matches = queries[(queries['matched_titles'] > 0) | (queries['matched_tags'] > 0)]

# Add columns to display the matched titles and tags
matches['full_matched_titles'] = matches['QUERY'].apply(
    lambda q: content_data.loc[content_data['title'].str.contains(q, na=False), 'title'].tolist()
)

matches['full_matched_tags'] = matches['QUERY'].apply(
    lambda q: content_data.loc[content_data['tags'].str.contains(q, na=False), 'tags'].tolist()
)

# Remove duplicates based on 'QUERY'
matches = matches.drop_duplicates(subset='QUERY')

# Display the filtered and deduplicated results with matched titles and tags
print(matches[['QUERY', 'matched_titles', 'matched_tags', 'full_matched_titles', 'full_matched_tags']])

                        QUERY  matched_titles  matched_tags  \
67                freerunning               0             2
72                       culo               1             1
131              the simpsons               1             1
134             myspace movie               0             1
171        brokeback mountain               1             2
200                   beatbox               4             5
250                      pedo               1             1
265              chuck norris               0             2
269                  my space               0             1
299   transformers theme song               0             1
379            something blue               1             0
578                  vogueing               0             1
602                    pacman               0             1
657                       tit              17            22
661         we are scientists               0             3
698                     naked              14            17
729                   pokemon               0             2
730             forever young               1             1
830              michael alig               0             1
904                     utube               3            16
927                 brokeback               1             2
1127                    boobs               0             1
1151                tech deck               0             1
1196              viral video               0             1
1214                     tube               3            18
1297              who are you               1             0
1304                    booty               1             0
1337                      you             113           119
1382               ronaldinho               1             7
1462                     sexy               3            18
1497                    lezbo               1             0
1564              music video             115           205
1587                  topless               0             1
1624                     huge               0             1
1717                   naruto               0             3
1724                   vegeta               2             5
1729                  shakira               0             2
1838           sleater kinney               0             3
1857                    kimbo               0             2
1883        myspace the movie               1             1
1975                     jeep               1             1

                                    full_matched_titles  \
67                                                   []
72            [pitbull  culo ft lil jon official video]
131              [vadrum meets the simpsons drum video]
134                                                  []
171              [quotfar awayquot  brokeback mountain]
200   [dharni beatbox, beatboxing trance, beatboxing...
250     [rovio mobile  war diary torpedo  game trailer]
265                                                  []
269                                                  []
299                                                  []
379                              [i see something blue]
578                                                  []
602                                                  []
657   [papas y mamas  daddies amp mummies english su...
661                                                  []
698   [iron amp wine  naked as we came official vide...
729                                                  []
730                         [youth group forever young]
830                                                  []
904   [byrd the leaves be green sound broken by yout...
927              [quotfar awayquot  brokeback mountain]
1127                                                 []
1151                                                 []
1196                                                 []
1214  [byrd the leaves be green sound broken by yout...
1297                [    who are you living for feat  ]
1304                                     [ms new booty]
1337  [stevie wonder  you are the sunshine of my lif...
1382                  [jogatv episode 10 ronaldinhojoy]
1462  [sexy bath  family feud, ti je sexy, sexy beij...
1497           [jorge gonzalezbongos cowbell and guiro]
1564  [the scene aesthetic  beauty in the breakdown ...
1587                                                 []
1624                                                 []
1717                                                 []
1724  [crazy over vegetables  cool tunes for kids by...
1729                                                 []
1838                                                 []
1857                                                 []
1883                       [myspace the movie official]
1975           [jeep willys  minha paixo  motoreseacao]

                                      full_matched_tags
67    [tricks stunts gymnastics martial arts parkour...
72    [pitbull rap video music lil jon crunk miami l...
131   [drums drumming drummer the simpsons simpsons ...
134   [facebook the movie myspace david lehre vendet...
171   [brokeback mountain jack ennis nickelback fanv...
200   [beatbox dharni singapore sg beatboxing, verba...
250   [rovio mobile game torpedo world war ii submar...
265   [p90 fn guns firearms herstal cool gun blue su...
269   [facebook the movie myspace david lehre vendet...
299   [transformers theme song music video smosh ant...
379                                                  []
578   [vogue vogueing voguing old new way malcolm mc...
602   [marvelous motiong sifu jun press play moon mr...
657   [braille musical artist braille braille  shade...
661   [lonely island we are scientists akiva schaffe...
698   [david lehre vendetta studios moliere play mus...
729   [smosh ian hecox anthony padilla theme song mu...
730   [youth group forever young casino twilight dog...
830   [club kids organization joan rivers musical ar...
904   [short film independent guerrilla filmmaking a...
927   [brokeback mountain jack ennis nickelback fanv...
1127  [power girl classifieds blinky productions taw...
1151  [skateboarding sponsor sponser me kickflip ska...
1196  [facebook the movie myspace david lehre vendet...
1214  [short film independent guerrilla filmmaking a...
1297                                                 []
1304                                                 []
1337  [morrissey irish blood english heart pop indie...
1382  [soccer football nike eric cantona joga bonito...
1462  [marvelous motiong sifu jun press play moon mr...
1497                                                 []
1564  [story year anthem our dying day music video, ...
1587  [bisexual indie film comedy nicole rayburn sex...
1624  [lion roar tiger vs attack big cat rescue prey...
1717  [ask a ninja ninja funny comedy naruto funny v...
1724  [vegetarian factory farm vegan chicken cow pig...
1729  [how to dance dancer dancing bellydance bellyd...
1838  [sleaterkinney sleater kinney rock, 2005 ytcro...
1857  [p90 fn guns firearms herstal cool gun blue su...
1883  [facebook the movie myspace david lehre vendet...
1975  [motores ao jeep willys minha paixo natal moto...

/var/folders/7r/8tzl4xz922146pgx3szt94t80000gn/T/ipykernel_60661/2761361353.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['full_matched_titles'] = matches['QUERY'].apply(
/var/folders/7r/8tzl4xz922146pgx3szt94t80000gn/T/ipykernel_60661/2761361353.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['full_matched_tags'] = matches['QUERY'].apply(

In [7]:
# Categories from your input
categories = {
    "Film & Animation", "Autos & Vehicles", "Music", "Pets & Animals", "Sports", 
    "Short Movies", "Travel & Events", "Gaming", "Videoblogging", "People & Blogs", 
    "Comedy", "Entertainment", "News & Politics", "Howto & Style", "Education", 
    "Science & Technology", "Nonprofits & Activism", "Movies", "Anime/Animation", 
    "Action/Adventure", "Classics", "Documentary", "Drama", "Family", "Foreign", 
    "Horror", "Sci-Fi/Fantasy", "Thriller", "Shorts", "Shows", "Trailers"
}

# Assign videos to categories based on matching tags
def categorize_tags(tags):
    if pd.isna(tags):
        return 'Uncategorized'
    tags = tags.lower()
    for category in categories:
        if category.lower() in tags:
            return category
    return 'Uncategorized'

content_data['category'] = content_data['tags'].apply(categorize_tags)

# Create hierarchy with a general category, specific category, and tags
general_categories = {
    'Education': ['Education', 'Science & Technology', 'Howto & Style'],
    'Music': ['Music'],
    'Movies': ['Film & Animation', 'Movies', 'Short Movies', 'Documentary', 'Drama'],
    'Entertainment': ['Entertainment', 'Comedy', 'People & Blogs', 'Shows'],
    'News & Politics': ['News & Politics'],
    'Gaming': ['Gaming'],
    'Travel': ['Travel & Events'],
    # Add more general categories and mappings as needed
}

def assign_general_category(category):
    for general, specifics in general_categories.items():
        if category in specifics:
            return general
    return 'Other'

content_data['general_category'] = content_data['category'].apply(assign_general_category)

# Display the hierarchy
hierarchy = content_data[['general_category', 'category', 'tags']].head()
print(hierarchy)

  general_category       category  \
0            Other  Uncategorized
1            Other  Uncategorized
2            Other  Uncategorized
3            Music          Music
4            Music          Music

                                                tags
0  mad world gary jules donnie darko michel gondr...
1                       mexico banda antonio aguilar
2  hilltop hoods nosebleed section simon brien fl...
3  sisters mercy eldritch lucretia reflection 80s...
4        story year anthem our dying day music video

In [9]:
# Filter out 'Uncategorized' categories
categorized_videos = content_data[content_data['category'] != 'Uncategorized']
print(categorized_videos)

# Display the unique categories that are not 'Uncategorized'
print(categorized_videos['category'].unique())

               publishedAt                 channelId  \
3     2006-01-24T21:13:53Z  UCPtUzr5y-aMmdfWurqNpHOg
4     2006-01-11T02:02:19Z  UCiPXAzD0HnGDHRCwleX2I2A
8     2006-01-25T19:19:21Z  UCY30JRSgfhYXA6i6xX1erWg
9     2006-01-14T01:44:43Z  UCCIKHL_vC_OAKLphvoXpNdg
16    2006-01-24T21:19:27Z  UCPtUzr5y-aMmdfWurqNpHOg
...                    ...                       ...
2580  2006-12-16T20:22:09Z  UCeG9ubc2KnEbQYGlIl45swQ
2601  2006-12-10T02:07:03Z  UC8pdWMu8TsTMrn5ngIjyD2w
2603  2006-12-17T21:09:42Z  UCXPBWg-9k6_-_SPtPYnpTqA
2611  2006-12-09T22:00:54Z  UCXPBWg-9k6_-_SPtPYnpTqA
2612  2006-12-09T23:51:27Z  UCXPBWg-9k6_-_SPtPYnpTqA

                                             title  \
3     the sisters of mercy  lucretia my reflection
4         story of the yearanthem of our dying day
8               teenage mutant ninja turtles theme
9       allison crowe  hallelujah  liveinthestudio
16                      the sisters of mercy  more
...                                            ...
2580                        tina karol    nochenka
2601                                  jingle bells
2603               disciples on the road to emmaus
2611                   dr bill pickett endorsement
2612                   irene sultzbach endorsement

                                            description  \
3     Music video by The Sisters of Mercy performing...
4     Story of the Year-Anthem Of Our Dying Day musi...
8     Teenage Mutant Ninja Turtles now has a skit an...
9     "It's, as I say, a desire to affirm my faith i...
16    Music video by The Sisters of Mercy performing...
...                                                 ...
2580             Released first on December 13th, 2006.
2601  The wonderful Christmas Carol "Jingle Bells" p...
2603  A presentation made to the Diocese of Brooklyn...
2611                                  Dr. Bill Pickett.
2612                       Irene Sultzbach endorsement.

                                             thumbnails  \
3     {'default': {'url': 'https://i.ytimg.com/vi/Iu...
4     {'default': {'url': 'https://i.ytimg.com/vi/PV...
8     {'default': {'url': 'https://i.ytimg.com/vi/6D...
9     {'default': {'url': 'https://i.ytimg.com/vi/vI...
16    {'default': {'url': 'https://i.ytimg.com/vi/qD...
...                                                 ...
2580  {'default': {'url': 'https://i.ytimg.com/vi/Bf...
2601  {'default': {'url': 'https://i.ytimg.com/vi/RM...
2603  {'default': {'url': 'https://i.ytimg.com/vi/id...
2611  {'default': {'url': 'https://i.ytimg.com/vi/y5...
2612  {'default': {'url': 'https://i.ytimg.com/vi/Jb...

               channelTitle liveBroadcastContent           publishTime  \
3              rhubarbcream                 none  2006-01-24T21:13:53Z
4                    cailin                 none  2006-01-11T02:02:19Z
8                     Smosh                 none  2006-01-25T19:19:21Z
9             Allison Crowe                 none  2006-01-14T01:44:43Z
16             rhubarbcream                 none  2006-01-24T21:19:27Z
...                     ...                  ...                   ...
2580               hermesfr                 none  2006-12-16T20:22:09Z
2601  pageantbarbie16 gadgf                 none  2006-12-10T02:07:03Z
2603        Richard McCorry                 none  2006-12-17T21:09:42Z
2611        Richard McCorry                 none  2006-12-09T22:00:54Z
2612        Richard McCorry                 none  2006-12-09T23:51:27Z

      viewCount  likeCount  dislikeCount  favoriteCount  commentCount  \
3      19002764   110564.0        2123.0              0        5920.0
4      16218874    69217.0        1579.0              0        4896.0
8      12477434    75295.0        8484.0              0        9685.0
9       9541173        NaN           NaN              0           NaN
16      6589042    31762.0         715.0              0        1559.0
...         ...        ...           ...            ...           ...
2580    3241206    13990.0         268.0              0        2099.0
2601     691048     1421.0          14.0              0         221.0
2603     644904     1554.0          46.0              0         210.0
2611  115044363   764312.0       19635.0              0       67440.0
2612   51249137   166871.0        4688.0              0       23477.0

                                                   tags   category  \
3     sisters mercy eldritch lucretia reflection 80s...      Music
4           story year anthem our dying day music video      Music
8     teenage mutant ninja turtles theme song music ...      Music
9     allison crowe chanson piano voice rock folk so...      Music
16    sisters mercy more 80s goth eldritch music off...      Music
...                                                 ...        ...
2580  tina karol eurovision  nochenka ukraine ukrain...      Music
2601                       christmas music jingle bells      Music
2603  spirituality change religion emmaus catholic c...  Education
2611  spirituality change religion emmaus catholic c...  Education
2612  spirituality change religion emmaus catholic c...  Education

     general_category
3               Music
4               Music
8               Music
9               Music
16              Music
...               ...
2580            Music
2601            Music
2603        Education
2611        Education
2612        Education

[667 rows x 16 columns]
['Music' 'Comedy' 'Documentary' 'Education' 'Horror' 'Entertainment'
 'Shows' 'Family' 'Movies' 'Sports' 'Gaming' 'Thriller' 'Classics'
 'Foreign' 'Drama']

In [ ]:
categorized_videos.to_excel('../Data/categorized_videos.xlsx')